### ISSUE TITLE
Time Zone Issue with ICS

### ISSUE THREAD

**Issue by jonathanhaslett** [darwinmakers/darwinmakers-site#6]
The calendar works. But everything is in UTC time which puts the events on a Thursday morning for Darwin time.
![image](https://user-images.githubusercontent.com/1563475/76042901-8ab76380-5f9d-11ea-919d-e3d516fcc8b4.png)

I suspect that we need to declare the time zone in the ICS file with something like this just before the BEGIN:VEVENT

```
BEGIN:VTIMEZONE
TZID:Australia/Darwin
TZURL:http://tzurl.org/zoneinfo-outlook/Australia/Darwin
X-LIC-LOCATION:Australia/Darwin
BEGIN:STANDARD
TZOFFSETFROM:+0930
TZOFFSETTO:+0930
TZNAME:ACST
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
```
Then we just drop the `Z` from the end of the various time fields (so that they use the time zone instead of UTC).

**Comment by jonathanhaslett** [comment]
https://stackoverflow.com/questions/35645402/how-to-specify-timezone-in-ics-file-which-will-work-efficiently-with-google-outl

**Comment by melvey** [comment]
Done. It won't work with daylight savings but that's not much of a problem for us
